//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Fusionpixel12pxzh_hans_ttf
    {
        public const string BundleName = "fusion-pixel-12px-zh_hans_ttf";
        public const string FUSIONPIXEL12PXZH_HANS = "fusion-pixel-12px-zh_hans";
    }
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string CLICK = "Click";
        public const string DAGGER = "Dagger";
        public const string DICEROLL = "DiceRoll";
        public const string ENEMYDEAD = "EnemyDead";
        public const string ENEMYHURT = "EnemyHurt";
        public const string GAMEPASS = "GamePass";
        public const string HOLYFIRE = "HolyFire";
        public const string HOLYFIREHIT = "HolyFireHit";
        public const string HOLYLIGHT = "HolyLight";
        public const string HUMANHURT = "HumanHurt";
        public const string LEVELUP = "LevelUp";
        public const string PICKUP = "PickUp";
        public const string PLAYERHURT = "PlayerHurt";
        public const string SWORD = "Sword";
        public const string SWORDIMPACT = "SwordImpact";
        public const string UPGRADE = "Upgrade";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uigamepasspanel_prefab
    {
        public const string BundleName = "uigamepasspanel_prefab";
        public const string UIGAMEPASSPANEL = "UIGamePassPanel";
    }
    public class Uigamestartpanel_prefab
    {
        public const string BundleName = "uigamestartpanel_prefab";
        public const string UIGAMESTARTPANEL = "UIGameStartPanel";
    }
}
